// Builds the deployable static site into web/dist/.
//
//  1. Inlines the sealed converter (core + UI + style) into one self-contained
//     HTML payload. It has no external resources, so once the shell has
//     downloaded it, nothing more is fetched.
//  2. Pins the payload's inline script and style by SHA-256 in both CSPs, and
//     pins the whole payload by SHA-384 (Subresource Integrity) in the shell.
//  3. Writes the shell pages with a <meta> CSP, and the host header files
//     (_headers for Netlify / Cloudflare Pages, headers.json for the local
//     server and the tests, and an nginx snippet) from src/policy.mjs.
//
// Deterministic: the same sources always produce byte-identical output.

import { createHash } from 'node:crypto';
import { mkdir, readFile, rm, writeFile, copyFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  INSTANCE_PLACEHOLDER,
  SEALED_FRAME_SANDBOX,
  SHELL_TRUSTED_TYPES_POLICY,
  sealedFrameCsp,
  shellCsp,
  siteHeaders,
} from './src/policy.mjs';
import { PROTOCOL_ID } from './src/shell/assets/protocol.js';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = join(ROOT, 'src');
export const DIST = join(ROOT, 'dist');
export const PAYLOAD_PATH = 'assets/sealed/image-converter.sealed.txt';

const sha = (alg, data) => createHash(alg).update(data, 'utf8').digest('base64');

function fill(template, values, label) {
  const out = template.replace(/\{\{([A-Z_]+)\}\}/g, (m, key) => {
    if (!(key in values)) throw new Error(`${label}: no value for {{${key}}}`);
    return values[key];
  });
  if (/\{\{[A-Z_]+\}\}/.test(out)) throw new Error(`${label}: unfilled placeholder`);
  return out;
}

export async function buildSealedPayload() {
  const read = (name) => readFile(join(SRC, 'sealed', name), 'utf8');
  const [core, workerProtocol, sealCheck, worker, ui, style, template] = await Promise.all([
    read('converter-core.js'),
    read('worker-protocol.js'),
    read('seal-check.js'),
    read('image-worker.js'),
    read('converter-ui.js'),
    read('image-converter.css'),
    read('image-converter.html'),
  ]);

  // The processing Worker's code. It is embedded as a string constant in the
  // frame's inline script, so the frame's script hash (and the payload's SRI
  // hash) pin it too. The frame turns it into a blob: URL to start Workers.
  const workerScript = ['(() => {', "'use strict';", core.trim(), workerProtocol.trim(), sealCheck.trim(), worker.trim(), '})();'].join('\n');

  // One IIFE, so nothing leaks onto the frame's window except through
  // deliberate assignments (there are none).
  const script = [
    '(() => {',
    "'use strict';",
    `const PROTOCOL_ID = ${JSON.stringify(PROTOCOL_ID)};`,
    `const WORKER_SOURCE = ${JSON.stringify(workerScript)};`,
    core.trim(),
    workerProtocol.trim(),
    sealCheck.trim(),
    ui.trim(),
    '})();',
  ].join('\n');

  for (const [label, code] of [['worker', workerScript], ['frame', script]]) {
    if (/<\/script|<!--/i.test(code)) throw new Error(`sealed ${label} script contains a sequence that would break inlining`);
  }
  if (/<\/style/i.test(style)) throw new Error('sealed style contains </style');

  const hashes = { scriptHash: sha('sha256', script), styleHash: sha('sha256', style) };
  const csp = sealedFrameCsp(hashes);
  const payload = fill(
    template,
    {
      SEALED_CSP: csp,
      SEALED_STYLE: style,
      SEALED_SCRIPT: script,
      INSTANCE_PLACEHOLDER,
    },
    'sealed payload',
  );
  return { payload, script, workerScript, style, hashes, csp, integrity: `sha384-${sha('sha384', payload)}` };
}

export async function build({ outDir = DIST, quiet = false } = {}) {
  const sealed = await buildSealedPayload();
  const shellMetaCsp = shellCsp(sealed.hashes, { forHeader: false });
  const shellHeaderCsp = shellCsp(sealed.hashes, { forHeader: true });
  const headers = siteHeaders(sealed.hashes);

  await rm(outDir, { recursive: true, force: true });
  await mkdir(join(outDir, 'assets/sealed'), { recursive: true });

  for (const page of ['index.html', 'image.html']) {
    const html = await readFile(join(SRC, 'shell', page), 'utf8');
    await writeFile(join(outDir, page), fill(html, { SHELL_CSP_META: shellMetaCsp }, page));
  }
  for (const asset of ['app.js', 'protocol.js', 'shell.css', 'icon.svg']) {
    await copyFile(join(SRC, 'shell/assets', asset), join(outDir, 'assets', asset));
  }

  await writeFile(join(outDir, PAYLOAD_PATH), sealed.payload);

  const manifest = {
    // Relative to assets/app.js, which resolves it against import.meta.url.
    path: './' + PAYLOAD_PATH.slice('assets/'.length),
    integrity: sealed.integrity,
    sandbox: SEALED_FRAME_SANDBOX,
    instancePlaceholder: INSTANCE_PLACEHOLDER,
    trustedTypesPolicy: SHELL_TRUSTED_TYPES_POLICY,
  };
  await writeFile(
    join(outDir, 'assets/sealed-manifest.js'),
    '// Generated by web/build.mjs. Do not edit: rebuild instead.\n' +
      `export const SEALED_TOOL = Object.freeze(${JSON.stringify(
        { ...manifest, sandbox: '__SANDBOX__' },
        null,
        2,
      ).replace('"__SANDBOX__"', `Object.freeze(${JSON.stringify(SEALED_FRAME_SANDBOX)})`)});\n`,
  );

  await writeFile(join(outDir, 'headers.json'), JSON.stringify(headers, null, 2) + '\n');
  await writeFile(join(outDir, '_headers'), toNetlifyHeaders(headers));
  await writeFile(join(outDir, 'nginx-security-headers.conf'), toNginx(headers[0].headers));

  const info = {
    payloadPath: PAYLOAD_PATH,
    integrity: sealed.integrity,
    scriptHash: sealed.hashes.scriptHash,
    workerSourceSha256: createHash('sha256').update(sealed.workerScript, 'utf8').digest('hex'),
    styleHash: sealed.hashes.styleHash,
    sandbox: SEALED_FRAME_SANDBOX.join(' '),
    sealedCsp: sealed.csp,
    shellCspHeader: shellHeaderCsp,
    shellCspMeta: shellMetaCsp,
  };
  await writeFile(join(outDir, 'build-info.json'), JSON.stringify(info, null, 2) + '\n');

  if (!quiet) {
    console.log(`OfflineSeal Web built into ${outDir}`);
    console.log(`  sealed payload ${PAYLOAD_PATH} (${Buffer.byteLength(sealed.payload)} bytes) ${sealed.integrity}`);
  }
  return info;
}

function toNetlifyHeaders(rules) {
  const lines = ['# Generated by web/build.mjs from src/policy.mjs. Netlify / Cloudflare Pages format.'];
  for (const { pattern, headers } of rules) {
    lines.push(pattern);
    for (const [name, value] of Object.entries(headers)) lines.push(`  ${name}: ${value}`);
  }
  return lines.join('\n') + '\n';
}

function toNginx(headers) {
  const lines = ['# Generated by web/build.mjs from src/policy.mjs. Include in every location that serves OfflineSeal Web.'];
  for (const [name, value] of Object.entries(headers)) {
    lines.push(`add_header ${name} "${value.replace(/"/g, '\\"')}" always;`);
  }
  return lines.join('\n') + '\n';
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  await build();
}
